version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pig_farm_postgres
    environment:
      POSTGRES_DB: pig_farm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./all.sql:/docker-entrypoint-initdb.d/all.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./BE-farm
      dockerfile: Dockerfile
    container_name: pig_farm_backend
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres:5432/pig_farm_db
      SECRET_KEY: your-secret-key-change-in-production
      DEBUG: true
    ports:
      - "8000:8000"
    volumes:
      - ./BE-farm:/app
      - /app/__pycache__
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ./FE-farm
      dockerfile: Dockerfile
    container_name: pig_farm_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./FE-farm:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api

volumes:
  postgres_data: