"""Initial migration

Revision ID: ad6f98d273d4
Revises: 
Create Date: 2025-09-22 10:30:27.492547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad6f98d273d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed Wagtail table drops as they are not part of our schema
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wagtailadmin_admin',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='wagtailadmin_admin_pkey')
    )
    op.create_table('django_migrations',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_migrations_pkey')
    )
    op.create_table('wagtailcore_pagesubscription',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('comment_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['wagtailcore_page.id'], name='wagtailcore_pagesubs_page_id_a085e7a6_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='wagtailcore_pagesubscription_user_id_89d7def9_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_pagesubscription_pkey'),
    sa.UniqueConstraint('page_id', 'user_id', name='wagtailcore_pagesubscription_page_id_user_id_0cef73ed_uniq')
    )
    op.create_index('wagtailcore_pagesubscription_user_id_89d7def9', 'wagtailcore_pagesubscription', ['user_id'], unique=False)
    op.create_index('wagtailcore_pagesubscription_page_id_a085e7a6', 'wagtailcore_pagesubscription', ['page_id'], unique=False)
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_user_permissions_pkey'),
    sa.UniqueConstraint('user_id', 'permission_id', name='auth_user_user_permissions_user_id_permission_id_14a6b632_uniq')
    )
    op.create_index('auth_user_user_permissions_user_id_a95ead1b', 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index('auth_user_user_permissions_permission_id_1fbb5f2c', 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('wagtailsearch_indexentry',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title_norm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('autocomplete', postgresql.TSVECTOR(), autoincrement=False, nullable=False),
    sa.Column('title', postgresql.TSVECTOR(), autoincrement=False, nullable=False),
    sa.Column('body', postgresql.TSVECTOR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='wagtailsearch_indexe_content_type_id_62ed694f_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailsearch_indexentry_pkey'),
    sa.UniqueConstraint('content_type_id', 'object_id', name='wagtailsearch_indexentry_content_type_id_object_i_bcd7ba73_uniq')
    )
    op.create_index('wagtailsearch_indexentry_content_type_id_62ed694f', 'wagtailsearch_indexentry', ['content_type_id'], unique=False)
    op.create_index('wagtailsear_title_9caae0_gin', 'wagtailsearch_indexentry', ['title'], unique=False, postgresql_using='gin')
    op.create_index('wagtailsear_body_90c85d_gin', 'wagtailsearch_indexentry', ['body'], unique=False, postgresql_using='gin')
    op.create_index('wagtailsear_autocom_476c89_gin', 'wagtailsearch_indexentry', ['autocomplete'], unique=False, postgresql_using='gin')
    op.create_table('wagtailcore_groupsitepermission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='wagtailcore_groupsit_group_id_e5cdbee4_fk_auth_grou', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='wagtailcore_groupsit_permission_id_459b1f38_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['site_id'], ['wagtailcore_site.id'], name='wagtailcore_groupsit_site_id_245de488_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_groupsitepermission_pkey'),
    sa.UniqueConstraint('group_id', 'site_id', 'permission_id', name='wagtailcore_groupsiteper_group_id_site_id_permiss_a58ee30d_uniq')
    )
    op.create_index('wagtailcore_groupsitepermission_site_id_245de488', 'wagtailcore_groupsitepermission', ['site_id'], unique=False)
    op.create_index('wagtailcore_groupsitepermission_permission_id_459b1f38', 'wagtailcore_groupsitepermission', ['permission_id'], unique=False)
    op.create_index('wagtailcore_groupsitepermission_group_id_e5cdbee4', 'wagtailcore_groupsitepermission', ['group_id'], unique=False)
    op.create_table('wagtailcore_pageviewrestriction_groups',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('pageviewrestriction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='wagtailcore_pageview_group_id_6460f223_fk_auth_grou', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['pageviewrestriction_id'], ['wagtailcore_pageviewrestriction.id'], name='wagtailcore_pageview_pageviewrestriction__f147a99a_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_pageviewrestriction_groups_pkey'),
    sa.UniqueConstraint('pageviewrestriction_id', 'group_id', name='wagtailcore_pageviewrest_pageviewrestriction_id_g_d23f80bb_uniq')
    )
    op.create_index('wagtailcore_pageviewrestriction_groups_group_id_6460f223', 'wagtailcore_pageviewrestriction_groups', ['group_id'], unique=False)
    op.create_index('wagtailcore_pageviewrestri_pageviewrestriction_id_f147a99a', 'wagtailcore_pageviewrestriction_groups', ['pageviewrestriction_id'], unique=False)
    op.create_table('wagtailcore_task',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='wagtailcore_task_content_type_id_249ab8ba_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_task_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('wagtailcore_task_content_type_id_249ab8ba', 'wagtailcore_task', ['content_type_id'], unique=False)
    op.create_table('wagtailcore_revision',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('approved_go_live_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('object_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('object_str', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['base_content_type_id'], ['django_content_type.id'], name='wagtailcore_revision_base_content_type_id_5b4ef7bd_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='wagtailcore_revision_content_type_id_c8cb69c0_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='wagtailcore_pagerevision_user_id_2409d2f4_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_pagerevision_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('wagtailcore_revision_content_type_id_c8cb69c0', 'wagtailcore_revision', ['content_type_id'], unique=False)
    op.create_index('wagtailcore_revision_base_content_type_id_5b4ef7bd', 'wagtailcore_revision', ['base_content_type_id'], unique=False)
    op.create_index('wagtailcore_pagerevision_user_id_2409d2f4', 'wagtailcore_revision', ['user_id'], unique=False)
    op.create_index('wagtailcore_pagerevision_created_at_66954e3b', 'wagtailcore_revision', ['created_at'], unique=False)
    op.create_index('wagtailcore_pagerevision_approved_go_live_at_e56afc67', 'wagtailcore_revision', ['approved_go_live_at'], unique=False)
    op.create_index('content_object_idx', 'wagtailcore_revision', ['content_type_id', 'object_id'], unique=False)
    op.create_index('base_content_object_idx', 'wagtailcore_revision', ['base_content_type_id', 'object_id'], unique=False)
    op.create_table('wagtailcore_commentreply',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['wagtailcore_comment.id'], name='wagtailcore_commentr_comment_id_afc7e027_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='wagtailcore_commentreply_user_id_d0b3b9c3_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_commentreply_pkey')
    )
    op.create_index('wagtailcore_commentreply_user_id_d0b3b9c3', 'wagtailcore_commentreply', ['user_id'], unique=False)
    op.create_index('wagtailcore_commentreply_comment_id_afc7e027', 'wagtailcore_commentreply', ['comment_id'], unique=False)
    op.create_table('lu_content_kind',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('lu_content_kind_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lu_content_kind_pkey'),
    sa.UniqueConstraint('code', name='lu_content_kind_code_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('wagtailusers_userprofile',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('submitted_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('approved_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('rejected_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preferred_language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('current_time_zone', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('avatar', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('updated_comments_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('dismissibles', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('density', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('contrast', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('keyboard_shortcuts', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='wagtailusers_userprofile_user_id_59c92331_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailusers_userprofile_pkey'),
    sa.UniqueConstraint('user_id', name='wagtailusers_userprofile_user_id_key')
    )
    op.create_table('wagtailcore_pageviewrestriction',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('restriction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['wagtailcore_page.id'], name='wagtailcore_pageview_page_id_15a8bea6_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_pageviewrestriction_pkey')
    )
    op.create_index('wagtailcore_pageviewrestriction_page_id_15a8bea6', 'wagtailcore_pageviewrestriction', ['page_id'], unique=False)
    op.create_table('wagtailcore_groupapprovaltask_groups',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('groupapprovaltask_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='wagtailcore_groupapp_group_id_2e64b61f_fk_auth_grou', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['groupapprovaltask_id'], ['wagtailcore_groupapprovaltask.task_ptr_id'], name='wagtailcore_groupapp_groupapprovaltask_id_9a9255ea_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_groupapprovaltask_groups_pkey'),
    sa.UniqueConstraint('groupapprovaltask_id', 'group_id', name='wagtailcore_groupapprova_groupapprovaltask_id_gro_bb5ee7eb_uniq')
    )
    op.create_index('wagtailcore_groupapprovaltask_groups_group_id_2e64b61f', 'wagtailcore_groupapprovaltask_groups', ['group_id'], unique=False)
    op.create_index('wagtailcore_groupapprovalt_groupapprovaltask_id_9a9255ea', 'wagtailcore_groupapprovaltask_groups', ['groupapprovaltask_id'], unique=False)
    op.create_table('wagtailredirects_redirect',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('old_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_permanent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('redirect_link', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('redirect_page_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('automatically_created', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('redirect_page_route_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['redirect_page_id'], ['wagtailcore_page.id'], name='wagtailredirects_red_redirect_page_id_b5728a8f_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['site_id'], ['wagtailcore_site.id'], name='wagtailredirects_red_site_id_780a0e1e_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailredirects_redirect_pkey'),
    sa.UniqueConstraint('old_path', 'site_id', name='wagtailredirects_redirect_old_path_site_id_783622d7_uniq')
    )
    op.create_index('wagtailredirects_redirect_site_id_780a0e1e', 'wagtailredirects_redirect', ['site_id'], unique=False)
    op.create_index('wagtailredirects_redirect_redirect_page_id_b5728a8f', 'wagtailredirects_redirect', ['redirect_page_id'], unique=False)
    op.create_index('wagtailredirects_redirect_old_path_bb35247b_like', 'wagtailredirects_redirect', ['old_path'], unique=False)
    op.create_index('wagtailredirects_redirect_old_path_bb35247b', 'wagtailredirects_redirect', ['old_path'], unique=False)
    op.create_table('wagtailembeds_embed',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('max_width', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('html', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('thumbnail_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('cache_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailembeds_embed_pkey'),
    sa.UniqueConstraint('hash', name='wagtailembeds_embed_hash_c9bd8c9a_uniq')
    )
    op.create_index('wagtailembeds_embed_hash_c9bd8c9a_like', 'wagtailembeds_embed', ['hash'], unique=False)
    op.create_index('wagtailembeds_embed_cache_until_26c94bb0', 'wagtailembeds_embed', ['cache_until'], unique=False)
    op.create_table('lu_dose_unit',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('lu_dose_unit_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lu_dose_unit_pkey'),
    sa.UniqueConstraint('code', name='lu_dose_unit_code_key')
    )
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    sa.UniqueConstraint('username', name='auth_user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_user_username_6821ab7c_like', 'auth_user', ['username'], unique=False)
    op.create_table('wagtailcore_workflow',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_workflow_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_content_type_pkey'),
    sa.UniqueConstraint('app_label', 'model', name='django_content_type_app_label_model_76bd3d3b_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_table('lu_medicine_line',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('lu_medicine_line_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lu_medicine_line_pkey'),
    sa.UniqueConstraint('name', name='lu_medicine_line_name_key')
    )
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    sa.UniqueConstraint('name', name='auth_group_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_group_name_a6ea08ec_like', 'auth_group', ['name'], unique=False)
    op.create_table('core_newsindexpage',
    sa.Column('page_ptr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('intro', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_ptr_id'], ['wagtailcore_page.id'], name='core_newsindexpage_page_ptr_id_ec830d3b_fk_wagtailcore_page_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('page_ptr_id', name='core_newsindexpage_pkey')
    )
    op.create_table('wagtailcore_referenceindex',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('to_object_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('model_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_path_hash', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('base_content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['base_content_type_id'], ['django_content_type.id'], name='wagtailcore_referenc_base_content_type_id_313cf40f_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='wagtailcore_referenc_content_type_id_766e0336_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['to_content_type_id'], ['django_content_type.id'], name='wagtailcore_referenc_to_content_type_id_93690bbd_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_referenceindex_pkey'),
    sa.UniqueConstraint('base_content_type_id', 'object_id', 'to_content_type_id', 'to_object_id', 'content_path_hash', name='wagtailcore_referenceind_base_content_type_id_obj_9e6ccd6a_uniq')
    )
    op.create_index('wagtailcore_referenceindex_to_content_type_id_93690bbd', 'wagtailcore_referenceindex', ['to_content_type_id'], unique=False)
    op.create_index('wagtailcore_referenceindex_content_type_id_766e0336', 'wagtailcore_referenceindex', ['content_type_id'], unique=False)
    op.create_index('wagtailcore_referenceindex_base_content_type_id_313cf40f', 'wagtailcore_referenceindex', ['base_content_type_id'], unique=False)
    op.create_table('auth_user_groups',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_groups_pkey'),
    sa.UniqueConstraint('user_id', 'group_id', name='auth_user_groups_user_id_group_id_94350c0c_uniq')
    )
    op.create_index('auth_user_groups_user_id_6a12ed8b', 'auth_user_groups', ['user_id'], unique=False)
    op.create_index('auth_user_groups_group_id_97559544', 'auth_user_groups', ['group_id'], unique=False)
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name='django_session_pkey')
    )
    op.create_index('django_session_session_key_c0390e0f_like', 'django_session', ['session_key'], unique=False)
    op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    op.create_table('wagtailimages_image',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('focal_point_x', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('focal_point_y', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('focal_point_width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('focal_point_height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.CheckConstraint('file_size >= 0', name='wagtailimages_image_file_size_check'),
    sa.CheckConstraint('focal_point_height >= 0', name='wagtailimages_image_focal_point_height_check'),
    sa.CheckConstraint('focal_point_width >= 0', name='wagtailimages_image_focal_point_width_check'),
    sa.CheckConstraint('focal_point_x >= 0', name='wagtailimages_image_focal_point_x_check'),
    sa.CheckConstraint('focal_point_y >= 0', name='wagtailimages_image_focal_point_y_check'),
    sa.ForeignKeyConstraint(['collection_id'], ['wagtailcore_collection.id'], name='wagtailimages_image_collection_id_c2f8af7e_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['auth_user.id'], name='wagtailimages_image_uploaded_by_user_id_5d73dc75_fk_auth_user', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailimages_image_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('wagtailimages_image_uploaded_by_user_id_5d73dc75', 'wagtailimages_image', ['uploaded_by_user_id'], unique=False)
    op.create_index('wagtailimages_image_file_hash_fb5bbb23_like', 'wagtailimages_image', ['file_hash'], unique=False)
    op.create_index('wagtailimages_image_file_hash_fb5bbb23', 'wagtailimages_image', ['file_hash'], unique=False)
    op.create_index('wagtailimages_image_created_at_86fa6cd4', 'wagtailimages_image', ['created_at'], unique=False)
    op.create_index('wagtailimages_image_collection_id_c2f8af7e', 'wagtailimages_image', ['collection_id'], unique=False)
    op.create_table('lu_pig_breed_line',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('lu_pig_breed_line_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lu_pig_breed_line_pkey'),
    sa.UniqueConstraint('name', name='lu_pig_breed_line_name_key')
    )
    op.create_table('wagtailcore_locale',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_locale_pkey'),
    sa.UniqueConstraint('language_code', name='wagtailcore_locale_language_code_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('wagtailcore_locale_language_code_03149338_like', 'wagtailcore_locale', ['language_code'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_group_permissions_pkey'),
    sa.UniqueConstraint('group_id', 'permission_id', name='auth_group_permissions_group_id_permission_id_0cd325b0_uniq')
    )
    op.create_index('auth_group_permissions_permission_id_84c5c92e', 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index('auth_group_permissions_group_id_b120cbf9', 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_permission_content_type_id_2f476e4b', 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('product_pig',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('product_pig_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('pig_type_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('breed_line_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unit_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('cover_image_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='product_pig_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_product_pig_soft_delete', 'product_pig', ['is_deleted', 'deleted_at'], unique=False)
    op.create_table('core_newscategorypage',
    sa.Column('page_ptr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('slug_override', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('parent_category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_ptr_id'], ['wagtailcore_page.id'], name='core_newscategorypag_page_ptr_id_ab45b04a_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['core_newscategorypage.page_ptr_id'], name='core_newscategorypag_parent_category_id_a054fc00_fk_core_news', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('page_ptr_id', name='core_newscategorypage_pkey')
    )
    op.create_index('core_newscategorypage_slug_override_8692fa72_like', 'core_newscategorypage', ['slug_override'], unique=False)
    op.create_index('core_newscategorypage_slug_override_8692fa72', 'core_newscategorypage', ['slug_override'], unique=False)
    op.create_index('core_newscategorypage_parent_category_id_a054fc00', 'core_newscategorypage', ['parent_category_id'], unique=False)
    op.create_table('wagtailcore_workflowtask',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['wagtailcore_task.id'], name='wagtailcore_workflow_task_id_ce7716fe_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['wagtailcore_workflow.id'], name='wagtailcore_workflow_workflow_id_b9717175_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_workflowtask_pkey'),
    sa.UniqueConstraint('workflow_id', 'task_id', name='wagtailcore_workflowtask_workflow_id_task_id_4ec7a62b_uniq')
    )
    op.create_index('wagtailcore_workflowtask_workflow_id_b9717175', 'wagtailcore_workflowtask', ['workflow_id'], unique=False)
    op.create_index('wagtailcore_workflowtask_task_id_ce7716fe', 'wagtailcore_workflowtask', ['task_id'], unique=False)
    op.create_table('wagtailcore_site',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_default_site', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('root_page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['root_page_id'], ['wagtailcore_page.id'], name='wagtailcore_site_root_page_id_e02fb95c_fk_wagtailcore_page_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_site_pkey'),
    sa.UniqueConstraint('hostname', 'port', name='wagtailcore_site_hostname_port_2c626d70_uniq')
    )
    op.create_index('wagtailcore_site_root_page_id_e02fb95c', 'wagtailcore_site', ['root_page_id'], unique=False)
    op.create_index('wagtailcore_site_hostname_96b20b46_like', 'wagtailcore_site', ['hostname'], unique=False)
    op.create_index('wagtailcore_site_hostname_96b20b46', 'wagtailcore_site', ['hostname'], unique=False)
    op.create_table('lu_unit',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('lu_unit_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lu_unit_pkey'),
    sa.UniqueConstraint('code', name='lu_unit_code_key')
    )
    op.create_table('wagtailcore_workflowstate',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('current_task_state_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('object_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requested_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['base_content_type_id'], ['django_content_type.id'], name='wagtailcore_workflow_base_content_type_id_a30dc576_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='wagtailcore_workflow_content_type_id_2bb78ce1_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['current_task_state_id'], ['wagtailcore_taskstate.id'], name='wagtailcore_workflow_current_task_state_i_3a1a0632_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['auth_user.id'], name='wagtailcore_workflow_requested_by_id_4090bca3_fk_auth_user', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['wagtailcore_workflow.id'], name='wagtailcore_workflow_workflow_id_1f18378f_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_workflowstate_pkey'),
    sa.UniqueConstraint('current_task_state_id', name='wagtailcore_workflowstate_current_task_state_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('workflowstate_ct_id_idx', 'wagtailcore_workflowstate', ['content_type_id', 'object_id'], unique=False)
    op.create_index('workflowstate_base_ct_id_idx', 'wagtailcore_workflowstate', ['base_content_type_id', 'object_id'], unique=False)
    op.create_index('wagtailcore_workflowstate_workflow_id_1f18378f', 'wagtailcore_workflowstate', ['workflow_id'], unique=False)
    op.create_index('wagtailcore_workflowstate_requested_by_id_4090bca3', 'wagtailcore_workflowstate', ['requested_by_id'], unique=False)
    op.create_index('wagtailcore_workflowstate_content_type_id_2bb78ce1', 'wagtailcore_workflowstate', ['content_type_id'], unique=False)
    op.create_index('wagtailcore_workflowstate_base_content_type_id_a30dc576', 'wagtailcore_workflowstate', ['base_content_type_id'], unique=False)
    op.create_index('unique_in_progress_workflow', 'wagtailcore_workflowstate', ['base_content_type_id', 'object_id'], unique=True, postgresql_where="((status)::text = ANY ((ARRAY['in_progress'::character varying, 'needs_changes'::character varying])::text[]))")
    op.create_table('core_medicineproductpage',
    sa.Column('page_ptr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('packaging', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('price_unit', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('price_total', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_ptr_id'], ['wagtailcore_page.id'], name='core_medicineproduct_page_ptr_id_22d33788_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('page_ptr_id', name='core_medicineproductpage_pkey')
    )
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name='django_admin_log_action_flag_check'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='django_admin_log_pkey')
    )
    op.create_index('django_admin_log_user_id_c564eba6', 'django_admin_log', ['user_id'], unique=False)
    op.create_index('django_admin_log_content_type_id_c4bce8eb', 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('wagtailadmin_editingsession',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_editing', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='wagtailadmin_editing_content_type_id_4df7730e_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='wagtailadmin_editingsession_user_id_6e1a9b70_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailadmin_editingsession_pkey')
    )
    op.create_index('wagtailadmin_editingsession_user_id_6e1a9b70', 'wagtailadmin_editingsession', ['user_id'], unique=False)
    op.create_index('wagtailadmin_editingsession_content_type_id_4df7730e', 'wagtailadmin_editingsession', ['content_type_id'], unique=False)
    op.create_index('wagtailadmi_content_717955_idx', 'wagtailadmin_editingsession', ['content_type_id', 'object_id'], unique=False)
    op.create_table('wagtailcore_uploadedfile',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('file', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('for_content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['for_content_type_id'], ['django_content_type.id'], name='wagtailcore_uploaded_for_content_type_id_b0fc87b2_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['auth_user.id'], name='wagtailcore_uploaded_uploaded_by_user_id_c7580fe8_fk_auth_user', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_uploadedfile_pkey')
    )
    op.create_index('wagtailcore_uploadedfile_uploaded_by_user_id_c7580fe8', 'wagtailcore_uploadedfile', ['uploaded_by_user_id'], unique=False)
    op.create_index('wagtailcore_uploadedfile_for_content_type_id_b0fc87b2', 'wagtailcore_uploadedfile', ['for_content_type_id'], unique=False)
    op.create_table('wagtailcore_modellogentry',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('content_changed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('revision_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='wagtailcore_modellog_content_type_id_68849e77_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_modellogentry_pkey')
    )
    op.create_index('wagtailcore_modellogentry_user_id_0278d1bf', 'wagtailcore_modellogentry', ['user_id'], unique=False)
    op.create_index('wagtailcore_modellogentry_timestamp_9694521b', 'wagtailcore_modellogentry', ['timestamp'], unique=False)
    op.create_index('wagtailcore_modellogentry_revision_id_df6ca33a', 'wagtailcore_modellogentry', ['revision_id'], unique=False)
    op.create_index('wagtailcore_modellogentry_object_id_e0e7d4ef_like', 'wagtailcore_modellogentry', ['object_id'], unique=False)
    op.create_index('wagtailcore_modellogentry_object_id_e0e7d4ef', 'wagtailcore_modellogentry', ['object_id'], unique=False)
    op.create_index('wagtailcore_modellogentry_content_type_id_68849e77', 'wagtailcore_modellogentry', ['content_type_id'], unique=False)
    op.create_index('wagtailcore_modellogentry_content_changed_8bc39742', 'wagtailcore_modellogentry', ['content_changed'], unique=False)
    op.create_index('wagtailcore_modellogentry_action_d2d856ee_like', 'wagtailcore_modellogentry', ['action'], unique=False)
    op.create_index('wagtailcore_modellogentry_action_d2d856ee', 'wagtailcore_modellogentry', ['action'], unique=False)
    op.create_table('taggit_tag',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='taggit_tag_pkey'),
    sa.UniqueConstraint('name', name='taggit_tag_name_key'),
    sa.UniqueConstraint('slug', name='taggit_tag_slug_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('taggit_tag_slug_6be58b2c_like', 'taggit_tag', ['slug'], unique=False)
    op.create_index('taggit_tag_name_58eb2ed9_like', 'taggit_tag', ['name'], unique=False)
    op.create_table('lu_pig_type',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('lu_pig_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lu_pig_type_pkey'),
    sa.UniqueConstraint('code', name='lu_pig_type_code_key')
    )
    op.create_table('wagtailcore_workflowpage',
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['wagtailcore_page.id'], name='wagtailcore_workflow_page_id_81e7bab6_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['wagtailcore_workflow.id'], name='wagtailcore_workflow_workflow_id_56f56ff6_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('page_id', name='wagtailcore_workflowpage_pkey')
    )
    op.create_index('wagtailcore_workflowpage_workflow_id_56f56ff6', 'wagtailcore_workflowpage', ['workflow_id'], unique=False)
    op.create_table('core_pigpage',
    sa.Column('page_ptr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_ptr_id'], ['wagtailcore_page.id'], name='core_pigpage_page_ptr_id_d731eb95_fk_wagtailcore_page_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('page_ptr_id', name='core_pigpage_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('wagtaildocs_document',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('uploaded_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.CheckConstraint('file_size >= 0', name='wagtaildocs_document_file_size_check'),
    sa.ForeignKeyConstraint(['collection_id'], ['wagtailcore_collection.id'], name='wagtaildocs_document_collection_id_23881625_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['auth_user.id'], name='wagtaildocs_document_uploaded_by_user_id_17258b41_fk_auth_user', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtaildocs_document_pkey')
    )
    op.create_index('wagtaildocs_document_uploaded_by_user_id_17258b41', 'wagtaildocs_document', ['uploaded_by_user_id'], unique=False)
    op.create_index('wagtaildocs_document_collection_id_23881625', 'wagtaildocs_document', ['collection_id'], unique=False)
    op.create_table('wagtailcore_taskstate',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revision_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workflow_state_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('finished_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='wagtailcore_taskstat_content_type_id_0a758fdc_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['finished_by_id'], ['auth_user.id'], name='wagtailcore_taskstate_finished_by_id_13f98229_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['wagtailcore_revision.id'], name='wagtailcore_taskstat_revision_id_df25a499_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['task_id'], ['wagtailcore_task.id'], name='wagtailcore_taskstate_task_id_c3677c34_fk_wagtailcore_task_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['workflow_state_id'], ['wagtailcore_workflowstate.id'], name='wagtailcore_taskstat_workflow_state_id_9239a775_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_taskstate_pkey')
    )
    op.create_index('wagtailcore_taskstate_workflow_state_id_9239a775', 'wagtailcore_taskstate', ['workflow_state_id'], unique=False)
    op.create_index('wagtailcore_taskstate_task_id_c3677c34', 'wagtailcore_taskstate', ['task_id'], unique=False)
    op.create_index('wagtailcore_taskstate_page_revision_id_9f52c88e', 'wagtailcore_taskstate', ['revision_id'], unique=False)
    op.create_index('wagtailcore_taskstate_finished_by_id_13f98229', 'wagtailcore_taskstate', ['finished_by_id'], unique=False)
    op.create_index('wagtailcore_taskstate_content_type_id_0a758fdc', 'wagtailcore_taskstate', ['content_type_id'], unique=False)
    op.create_table('lu_medicine_category',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('lu_medicine_category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lu_medicine_category_pkey'),
    sa.UniqueConstraint('name', name='lu_medicine_category_name_key'),
    sa.UniqueConstraint('slug', name='lu_medicine_category_slug_key')
    )
    op.create_table('wagtailcore_groupcollectionpermission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['wagtailcore_collection.id'], name='wagtailcore_groupcol_collection_id_5423575a_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='wagtailcore_groupcol_group_id_05d61460_fk_auth_grou', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='wagtailcore_groupcol_permission_id_1b626275_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_groupcollectionpermission_pkey'),
    sa.UniqueConstraint('group_id', 'collection_id', 'permission_id', name='wagtailcore_groupcollect_group_id_collection_id_p_a21cefe9_uniq')
    )
    op.create_index('wagtailcore_groupcollectionpermission_permission_id_1b626275', 'wagtailcore_groupcollectionpermission', ['permission_id'], unique=False)
    op.create_index('wagtailcore_groupcollectionpermission_group_id_05d61460', 'wagtailcore_groupcollectionpermission', ['group_id'], unique=False)
    op.create_index('wagtailcore_groupcollectionpermission_collection_id_5423575a', 'wagtailcore_groupcollectionpermission', ['collection_id'], unique=False)
    op.create_table('wagtailcore_workflowcontenttype',
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='wagtailcore_workflow_content_type_id_b261bb37_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['wagtailcore_workflow.id'], name='wagtailcore_workflow_workflow_id_9aad7cd2_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('content_type_id', name='wagtailcore_workflowcontenttype_pkey')
    )
    op.create_index('wagtailcore_workflowcontenttype_workflow_id_9aad7cd2', 'wagtailcore_workflowcontenttype', ['workflow_id'], unique=False)
    op.create_table('taggit_taggeditem',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='taggit_taggeditem_content_type_id_9957a03c_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['taggit_tag.id'], name='taggit_taggeditem_tag_id_f4f5b767_fk_taggit_tag_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='taggit_taggeditem_pkey'),
    sa.UniqueConstraint('content_type_id', 'object_id', 'tag_id', name='taggit_taggeditem_content_type_id_object_id_tag_id_4bb97a8e_uni')
    )
    op.create_index('taggit_taggeditem_tag_id_f4f5b767', 'taggit_taggeditem', ['tag_id'], unique=False)
    op.create_index('taggit_taggeditem_object_id_e2d7d1df', 'taggit_taggeditem', ['object_id'], unique=False)
    op.create_index('taggit_taggeditem_content_type_id_9957a03c', 'taggit_taggeditem', ['content_type_id'], unique=False)
    op.create_index('taggit_tagg_content_8fc721_idx', 'taggit_taggeditem', ['content_type_id', 'object_id'], unique=False)
    op.create_table('product_medicine',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('packaging', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price_unit', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('price_total', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='product_medicine_pkey')
    )
    op.create_index('idx_product_medicine_soft_delete', 'product_medicine', ['is_deleted', 'deleted_at'], unique=False)
    op.create_table('wagtailcore_grouppagepermission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='wagtailcore_grouppag_group_id_fc07e671_fk_auth_grou', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['page_id'], ['wagtailcore_page.id'], name='wagtailcore_grouppag_page_id_710b114a_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='wagtailcore_grouppag_permission_id_05acb22e_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_grouppagepermission_pkey'),
    sa.UniqueConstraint('group_id', 'page_id', 'permission_id', name='unique_permission')
    )
    op.create_index('wagtailcore_grouppagepermission_permission_id_05acb22e', 'wagtailcore_grouppagepermission', ['permission_id'], unique=False)
    op.create_index('wagtailcore_grouppagepermission_page_id_710b114a', 'wagtailcore_grouppagepermission', ['page_id'], unique=False)
    op.create_index('wagtailcore_grouppagepermission_group_id_fc07e671', 'wagtailcore_grouppagepermission', ['group_id'], unique=False)
    op.create_table('wagtailcore_collectionviewrestriction_groups',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('collectionviewrestriction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collectionviewrestriction_id'], ['wagtailcore_collectionviewrestriction.id'], name='wagtailcore_collecti_collectionviewrestri_47320efd_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='wagtailcore_collecti_group_id_1823f2a3_fk_auth_grou', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_collectionviewrestriction_groups_pkey'),
    sa.UniqueConstraint('collectionviewrestriction_id', 'group_id', name='wagtailcore_collectionvi_collectionviewrestrictio_988995ae_uniq')
    )
    op.create_index('wagtailcore_collectionviewrestriction_groups_group_id_1823f2a3', 'wagtailcore_collectionviewrestriction_groups', ['group_id'], unique=False)
    op.create_index('wagtailcore_collectionview_collectionviewrestriction__47320efd', 'wagtailcore_collectionviewrestriction_groups', ['collectionviewrestriction_id'], unique=False)
    op.create_table('wagtailcore_collectionviewrestriction',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('restriction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['wagtailcore_collection.id'], name='wagtailcore_collecti_collection_id_761908ec_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_collectionviewrestriction_pkey')
    )
    op.create_index('wagtailcore_collectionviewrestriction_collection_id_761908ec', 'wagtailcore_collectionviewrestriction', ['collection_id'], unique=False)
    op.create_table('core_newspage',
    sa.Column('page_ptr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('slug_override', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('author_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cover_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cover_id'], ['wagtailimages_image.id'], name='core_newspage_cover_id_94feb662_fk_wagtailimages_image_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['page_ptr_id'], ['wagtailcore_page.id'], name='core_newspage_page_ptr_id_7128a9c4_fk_wagtailcore_page_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('page_ptr_id', name='core_newspage_pkey')
    )
    op.create_index('core_newspage_slug_override_fcbffbca_like', 'core_newspage', ['slug_override'], unique=False)
    op.create_index('core_newspage_slug_override_fcbffbca', 'core_newspage', ['slug_override'], unique=False)
    op.create_index('core_newspage_cover_id_94feb662', 'core_newspage', ['cover_id'], unique=False)
    op.create_table('wagtailimages_rendition',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('file', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('focal_point_key', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('filter_spec', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['wagtailimages_image.id'], name='wagtailimages_rendit_image_id_3e1fd774_fk_wagtailim', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailimages_rendition_pkey'),
    sa.UniqueConstraint('image_id', 'filter_spec', 'focal_point_key', name='wagtailimages_rendition_image_id_filter_spec_foc_323c8fe0_uniq')
    )
    op.create_index('wagtailimages_rendition_image_id_3e1fd774', 'wagtailimages_rendition', ['image_id'], unique=False)
    op.create_index('wagtailimages_rendition_filter_spec_1cba3201_like', 'wagtailimages_rendition', ['filter_spec'], unique=False)
    op.create_index('wagtailimages_rendition_filter_spec_1cba3201', 'wagtailimages_rendition', ['filter_spec'], unique=False)
    op.create_table('pig_images',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pig_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('image_type', sa.VARCHAR(length=50), server_default=sa.text("'gallery'::character varying"), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pig_id'], ['product_pig.id'], name='fk_pig_images_pig_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pig_images_pkey')
    )
    op.create_index('idx_pig_images_type', 'pig_images', ['image_type'], unique=False)
    op.create_index('idx_pig_images_soft_delete', 'pig_images', ['is_deleted', 'deleted_at'], unique=False)
    op.create_index('idx_pig_images_published', 'pig_images', ['is_published'], unique=False)
    op.create_index('idx_pig_images_pig_id', 'pig_images', ['pig_id'], unique=False)
    op.create_index('idx_pig_images_created_at', 'pig_images', ['created_at'], unique=False)
    op.create_table('home_homepage',
    sa.Column('page_ptr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_ptr_id'], ['wagtailcore_page.id'], name='home_homepage_page_ptr_id_e5b77cf7_fk_wagtailcore_page_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('page_ptr_id', name='home_homepage_pkey')
    )
    op.create_table('cms_content_entry',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('kind_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('body_html', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('external_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cover_image_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('author_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seo_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seo_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['kind_id'], ['lu_content_kind.id'], name='cms_content_entry_kind_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cms_content_entry_pkey'),
    sa.UniqueConstraint('kind_id', 'slug', name='uq_cms_kind_slug')
    )
    op.create_index('idx_cms_title_trgm', 'cms_content_entry', [sa.literal_column('lower(title)')], unique=False, postgresql_using='gin')
    op.create_index('idx_cms_slug_trgm', 'cms_content_entry', [sa.literal_column('lower(slug)')], unique=False, postgresql_using='gin')
    op.create_index('idx_cms_kind_pub_time', 'cms_content_entry', ['kind_id', 'is_published', sa.literal_column('published_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('idx_cms_content_entry_soft_delete', 'cms_content_entry', ['is_deleted', 'deleted_at'], unique=False)
    op.create_table('wagtailcore_collection',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('depth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numchild', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.CheckConstraint('depth >= 0', name='wagtailcore_collection_depth_check'),
    sa.CheckConstraint('numchild >= 0', name='wagtailcore_collection_numchild_check'),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_collection_pkey'),
    sa.UniqueConstraint('path', name='wagtailcore_collection_path_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('wagtailcore_collection_path_d848dc19_like', 'wagtailcore_collection', ['path'], unique=False)
    op.create_table('wagtailforms_formsubmission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('submit_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['wagtailcore_page.id'], name='wagtailforms_formsub_page_id_e48e93e7_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailforms_formsubmission_pkey')
    )
    op.create_index('wagtailforms_formsubmission_page_id_e48e93e7', 'wagtailforms_formsubmission', ['page_id'], unique=False)
    op.create_table('wagtailcore_pagelogentry',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('content_changed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revision_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='wagtailcore_pageloge_content_type_id_74e7708a_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_pagelogentry_pkey')
    )
    op.create_index('wagtailcore_pagelogentry_user_id_604ccfd8', 'wagtailcore_pagelogentry', ['user_id'], unique=False)
    op.create_index('wagtailcore_pagelogentry_timestamp_deb774c4', 'wagtailcore_pagelogentry', ['timestamp'], unique=False)
    op.create_index('wagtailcore_pagelogentry_revision_id_8043d103', 'wagtailcore_pagelogentry', ['revision_id'], unique=False)
    op.create_index('wagtailcore_pagelogentry_page_id_8464e327', 'wagtailcore_pagelogentry', ['page_id'], unique=False)
    op.create_index('wagtailcore_pagelogentry_content_type_id_74e7708a', 'wagtailcore_pagelogentry', ['content_type_id'], unique=False)
    op.create_index('wagtailcore_pagelogentry_content_changed_99f27ade', 'wagtailcore_pagelogentry', ['content_changed'], unique=False)
    op.create_index('wagtailcore_pagelogentry_action_c2408198_like', 'wagtailcore_pagelogentry', ['action'], unique=False)
    op.create_index('wagtailcore_pagelogentry_action_c2408198', 'wagtailcore_pagelogentry', ['action'], unique=False)
    op.create_table('wagtailcore_page',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('depth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numchild', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('live', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('has_unpublished_changes', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('url_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('seo_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('show_in_menus', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('search_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('go_live_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expire_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expired', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('locked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('latest_revision_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('first_published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('live_revision_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('draft_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('locked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('locked_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('translation_key', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('locale_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alias_of_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latest_revision_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('depth >= 0', name='wagtailcore_page_depth_check'),
    sa.CheckConstraint('numchild >= 0', name='wagtailcore_page_numchild_check'),
    sa.ForeignKeyConstraint(['alias_of_id'], ['wagtailcore_page.id'], name='wagtailcore_page_alias_of_id_12945502_fk_wagtailcore_page_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='wagtailcore_page_content_type_id_c28424df_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['latest_revision_id'], ['wagtailcore_revision.id'], name='wagtailcore_page_latest_revision_id_e60fef51_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['live_revision_id'], ['wagtailcore_revision.id'], name='wagtailcore_page_live_revision_id_930bd822_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['locale_id'], ['wagtailcore_locale.id'], name='wagtailcore_page_locale_id_3c7e30a6_fk_wagtailcore_locale_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['locked_by_id'], ['auth_user.id'], name='wagtailcore_page_locked_by_id_bcb86245_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['auth_user.id'], name='wagtailcore_page_owner_id_fbf7c332_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_page_pkey'),
    sa.UniqueConstraint('path', name='wagtailcore_page_path_key'),
    sa.UniqueConstraint('translation_key', 'locale_id', name='wagtailcore_page_translation_key_locale_id_9b041bad_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_index('wagtailcore_page_slug_e7c11b8f_like', 'wagtailcore_page', ['slug'], unique=False)
    op.create_index('wagtailcore_page_slug_e7c11b8f', 'wagtailcore_page', ['slug'], unique=False)
    op.create_index('wagtailcore_page_path_98eba2c8_like', 'wagtailcore_page', ['path'], unique=False)
    op.create_index('wagtailcore_page_owner_id_fbf7c332', 'wagtailcore_page', ['owner_id'], unique=False)
    op.create_index('wagtailcore_page_locked_by_id_bcb86245', 'wagtailcore_page', ['locked_by_id'], unique=False)
    op.create_index('wagtailcore_page_locale_id_3c7e30a6', 'wagtailcore_page', ['locale_id'], unique=False)
    op.create_index('wagtailcore_page_live_revision_id_930bd822', 'wagtailcore_page', ['live_revision_id'], unique=False)
    op.create_index('wagtailcore_page_latest_revision_id_e60fef51', 'wagtailcore_page', ['latest_revision_id'], unique=False)
    op.create_index('wagtailcore_page_first_published_at_2b5dd637', 'wagtailcore_page', ['first_published_at'], unique=False)
    op.create_index('wagtailcore_page_content_type_id_c28424df', 'wagtailcore_page', ['content_type_id'], unique=False)
    op.create_index('wagtailcore_page_alias_of_id_12945502', 'wagtailcore_page', ['alias_of_id'], unique=False)
    op.create_table('news_categories',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), server_default=sa.text("'#0066CC'::character varying"), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), server_default=sa.text("'fa-folder'::character varying"), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['news_categories.id'], name='fk_news_categories_parent_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='news_categories_pkey'),
    sa.UniqueConstraint('slug', name='news_categories_slug_key')
    )
    op.create_index('idx_news_categories_sort', 'news_categories', ['sort_order'], unique=False)
    op.create_index('idx_news_categories_soft_delete', 'news_categories', ['is_deleted', 'deleted_at'], unique=False)
    op.create_index('idx_news_categories_slug', 'news_categories', ['slug'], unique=False)
    op.create_index('idx_news_categories_published', 'news_categories', ['is_published'], unique=False)
    op.create_index('idx_news_categories_parent', 'news_categories', ['parent_id'], unique=False)
    op.create_table('core_pigimagepage',
    sa.Column('page_ptr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pig_reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['wagtailimages_image.id'], name='core_pigimagepage_image_id_0f48f483_fk_wagtailimages_image_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['page_ptr_id'], ['wagtailcore_page.id'], name='core_pigimagepage_page_ptr_id_19ca9b21_fk_wagtailcore_page_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['pig_reference_id'], ['core_pigpage.page_ptr_id'], name='core_pigimagepage_pig_reference_id_15c1629f_fk_core_pigp', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('page_ptr_id', name='core_pigimagepage_pkey')
    )
    op.create_index('core_pigimagepage_pig_reference_id_15c1629f', 'core_pigimagepage', ['pig_reference_id'], unique=False)
    op.create_index('core_pigimagepage_image_id_0f48f483', 'core_pigimagepage', ['image_id'], unique=False)
    op.create_table('wagtailcore_groupapprovaltask',
    sa.Column('task_ptr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_ptr_id'], ['wagtailcore_task.id'], name='wagtailcore_groupapp_task_ptr_id_cfe58781_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('task_ptr_id', name='wagtailcore_groupapprovaltask_pkey')
    )
    op.create_table('wagtailcore_comment',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('contentpath', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('position', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resolved_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('revision_created_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['wagtailcore_page.id'], name='wagtailcore_comment_page_id_108444b5_fk_wagtailcore_page_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['auth_user.id'], name='wagtailcore_comment_resolved_by_id_a282aa0e_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['revision_created_id'], ['wagtailcore_revision.id'], name='wagtailcore_comment_revision_created_id_1d058279_fk_wagtailco', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='wagtailcore_comment_user_id_0c577ca6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='wagtailcore_comment_pkey')
    )
    op.create_index('wagtailcore_comment_user_id_0c577ca6', 'wagtailcore_comment', ['user_id'], unique=False)
    op.create_index('wagtailcore_comment_revision_created_id_1d058279', 'wagtailcore_comment', ['revision_created_id'], unique=False)
    op.create_index('wagtailcore_comment_resolved_by_id_a282aa0e', 'wagtailcore_comment', ['resolved_by_id'], unique=False)
    op.create_index('wagtailcore_comment_page_id_108444b5', 'wagtailcore_comment', ['page_id'], unique=False)
    # ### end Alembic commands ###
