# Generated by Django 5.2.6 on 2025-09-06 07:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Main content for the homepage', verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_en',
            field=wagtail.fields.RichTextField(blank=True, help_text='Main content for the homepage', null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_vi',
            field=wagtail.fields.RichTextField(blank=True, help_text='Main content for the homepage', null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, help_text='Text displayed on the main call-to-action button', max_length=100, verbose_name='Call to Action Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text_en',
            field=models.CharField(blank=True, help_text='Text displayed on the main call-to-action button', max_length=100, null=True, verbose_name='Call to Action Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text_vi',
            field=models.CharField(blank=True, help_text='Text displayed on the main call-to-action button', max_length=100, null=True, verbose_name='Call to Action Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Subtitle displayed below the main title', max_length=500, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, help_text='Subtitle displayed below the main title', max_length=500, null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle_vi',
            field=models.CharField(blank=True, help_text='Subtitle displayed below the main title', max_length=500, null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Main title displayed on the homepage hero section', max_length=200, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_en',
            field=models.CharField(blank=True, help_text='Main title displayed on the homepage hero section', max_length=200, null=True, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_vi',
            field=models.CharField(blank=True, help_text='Main title displayed on the homepage hero section', max_length=200, null=True, verbose_name='Hero Title'),
        ),
    ]
