# Generated by Django 5.2.6 on 2025-09-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsContentEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind_id', models.SmallIntegerField()),
                ('slug', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cms_content_entry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('packaging', models.TextField(blank=True, null=True)),
                ('price_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_medicine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_pig',
                'managed': False,
            },
        ),
    ]
