# Generated by Django 5.2.6 on 2025-09-14 15:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medicineproductpage_pigpage'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PigImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField()),
                ('pig_id', models.BigIntegerField(blank=True, null=True)),
                ('image_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pig_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('external_id', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về danh mục này')),
                ('color', models.CharField(blank=True, default='#0066CC', help_text='Mã màu hex (ví dụ: #FF0000 cho màu đỏ)', max_length=7)),
                ('icon', models.CharField(choices=[('fa-newspaper', 'Báo chí'), ('fa-bullhorn', 'Thông báo'), ('fa-calendar', 'Sự kiện'), ('fa-star', 'Nổi bật'), ('fa-tag', 'Thẻ'), ('fa-folder', 'Thư mục'), ('fa-heart', 'Yêu thích'), ('fa-fire', 'Hot')], default='fa-folder', help_text='Biểu tượng hiển thị cho danh mục', max_length=50)),
                ('sort_order', models.IntegerField(default=0, help_text='Số thứ tự (0-1000, số nhỏ hiển thị trước)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('slug_override', models.SlugField(blank=True, help_text='URL slug tùy chỉnh (để trống sẽ tự tạo từ tiêu đề)', max_length=255)),
                ('parent_category', models.ForeignKey(blank=True, help_text='Danh mục cha (để trống nếu là danh mục gốc)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='core.newscategorypage')),
            ],
            options={
                'verbose_name': 'Danh mục tin tức',
                'verbose_name_plural': 'Danh mục tin tức',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PigImagePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('external_id', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về hình ảnh')),
                ('image_type', models.CharField(choices=[('main', 'Ảnh chính'), ('gallery', 'Ảnh thư viện'), ('thumbnail', 'Ảnh thu nhỏ'), ('profile', 'Ảnh hồ sơ')], default='gallery', help_text='Loại hình ảnh', max_length=50)),
                ('file_size', models.IntegerField(blank=True, editable=False, null=True)),
                ('width', models.IntegerField(blank=True, editable=False, null=True)),
                ('height', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, help_text='Chọn hình ảnh lợn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('pig_reference', models.ForeignKey(blank=True, help_text='Chọn lợn liên quan đến hình ảnh này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='core.pigpage')),
            ],
            options={
                'verbose_name': 'Hình ảnh lợn',
                'verbose_name_plural': 'Hình ảnh lợn',
            },
            bases=('wagtailcore.page',),
        ),
    ]
