# Generated by Django 5.2.6 on 2025-09-15 14:09

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newscategory_pigimage_newscategorypage_pigimagepage'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsNewsEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind_id', models.SmallIntegerField()),
                ('slug', models.TextField()),
                ('title', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('body_json', models.JSONField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('external_url', models.TextField(blank=True, null=True)),
                ('cover_image_id', models.BigIntegerField(blank=True, null=True)),
                ('author_name', models.TextField(blank=True, null=True)),
                ('seo_title', models.TextField(blank=True, null=True)),
                ('seo_desc', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_content_entry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('featured_image', models.TextField(blank=True, null=True)),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('read_time', models.IntegerField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('tags', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Giới thiệu về trang tin tức')),
            ],
            options={
                'verbose_name': 'News Index Page',
                'verbose_name_plural': 'News Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('external_id', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('summary', models.CharField(blank=True, help_text='Tóm tắt ngắn cho danh sách', max_length=300)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Ngày phát hành')),
                ('slug_override', models.SlugField(blank=True, help_text='Để trống sẽ tự tạo từ tiêu đề', max_length=255)),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('image', 1), ('embed', 2), ('quote', 3), ('button', 6)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link', 'h2', 'h3']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Dán URL YouTube/Facebook...'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.URLBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('label', 4), ('url', 5)]], {})})),
                ('author_name', models.CharField(blank=True, help_text='Tên tác giả', max_length=255)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
            },
            bases=('wagtailcore.page',),
        ),
    ]
