# Generated by Django 5.2.6 on 2025-09-16 15:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cmsnewsentry_newsarticle_newsindexpage_newspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1), ('embed', 2), ('quote', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link', 'h2', 'h3']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Dán URL YouTube/Facebook...'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {})}),
        ),
    ]
